[package]
name = "concoct-web"
version = "0.1.0-alpha.1"
edition = "2021"

[dependencies]
concoct = "0.17.0-alpha.2"
web-sys = { version = "0.3.66", features = ["Document", "Event", "HtmlElement", "HtmlCollection", "Text", "Window"] }
